SELECT 
      TO_NUMBER(TO_CHAR(C.SALES_DATE, 'YYYY')) YEAR
    , TO_NUMBER(TO_CHAR(C.SALES_DATE, 'MM')) MONTH
    , COUNT(DISTINCT(B.USER_ID)) PUCHASED_USERS
    , ROUND(COUNT(DISTINCT(B.USER_ID))/A.DENOM,1) PUCHASED_RATIO
FROM 
    (SELECT 
          COUNT(*) DENOM
    FROM 
          USER_INFO 
    WHERE 
            TO_CHAR(JOINED, 'YYYY')=2021) A
          , (SELECT 
                  USER_ID
            FROM 
                  USER_INFO
            WHERE 
                  TO_CHAR(JOINED, 'YYYY')=2021) B 
JOIN ONLINE_SALE C ON B.USER_ID = C.USER_ID
GROUP BY 
      TO_CHAR(SALES_DATE, 'YYYY'), TO_CHAR(SALES_DATE, 'MM'), A.DENOM
ORDER BY 
      TO_CHAR(C.SALES_DATE, 'YYYY'), TO_CHAR(C.SALES_DATE, 'MM');